import React from 'react';
import ReactDOM from 'react-dom';


class TableRow extends React.Component {
    render() {
        return (
            <tr>
                <td>{this.props.name}</td>
                <td>{this.props.number}</td>
            </tr>
        )
    }
}


class Main extends React.Component {

    constructor() {
        super();

        this.state = {data: "Loading...", loaded: false};
        this.getDataFromApi();
    }

    getDataFromApi() {
        let apiurl = 'https://beta.randomapi.com/api/06ee19262a218d740d925e14f31d2498?results=40';

        let request = new XMLHttpRequest();
        request.onload = () => {
            this.setState({data: JSON.parse(request.response), loaded: true});
        };

        request.open("GET", apiurl);
        request.send();
    }

    render() {
        let loadingText = 'Loading...';
        let contents = [];
        if (this.state.loaded) {
            let results = this.state.data.results;
            console.log(results);
            for (let i = 0; i < results.length; i++) {
                console.log(contents);
                contents.push(<TableRow key={i} name={results[i].name} number={results[i].value}/>);
            }
            loadingText = '';
        }

        return (
            <div>
                <p>Hello there, HURR DURR! I am a react component, and here is some data from a random api (generated by <a href="https://beta.randomapi.com/">randomapi.com</a>) - enjoy!</p>
                {loadingText}
                <table>
                    <tbody>
                        {contents}
                    </tbody>
                </table>
            </div>

        );
    }
}

ReactDOM.render(<Main />, document.getElementById('main-demo-stuff'));